// <auto-generated />
using EFCodeFirstApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCodeFirstApp.DataAccess.Migrations
{
    [DbContext(typeof(TDbContext))]
    partial class TDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCodeFirstApp.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Milanes",
                            Code = 333422,
                            Name = "Rafael"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Cage",
                            Code = 775647,
                            Name = "Johnny"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Lindgren",
                            Code = 9873,
                            Name = "Anna"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Pérez",
                            Code = 112342,
                            Name = "Juanete"
                        },
                        new
                        {
                            Id = 5,
                            Author = "SuperNew",
                            Code = 7746398,
                            Name = "New"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
